### ISSUE TITLE
[Mod/Exception] java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/event/RegisterPayloadHandlerEvent

### ISSUE THREAD

**Issue by LunarN0v4** [JDDev0/EnergizedPower#32]
Error was caught during game startup on NeoForge 20.4.69-beta and Minecraft 1.20.4 with LWJGL 3.3.2 (No Java Agents):
```[01Jan2024 12:25:14.241] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: energizedpower, class me.jddev0.ep.EnergizedPowerMod
java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/event/RegisterPayloadHandlerEvent
	at me.jddev0.ep.EnergizedPowerMod.<init>(EnergizedPowerMod.java:72) ~[energizedpower-1.20.4-2.6.5-neoforge.jar%23233!/:1.20.4-2.6.5-neoforge]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:112) ~[language-java-2.0.7.jar%23262!/:2.0]
	at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:130) ~[core-2.0.7.jar%23261!/:2.0]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.neoforged.neoforge.network.event.RegisterPayloadHandlerEvent
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:197) ~[securejarhandler-2.1.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 15 more

**Comment by JDDev0** [comment]
Energized power version 1.20.4-2.6.5 requires NeoForge 20.4.70-beta or newer ![Graphics](https://github.com/JDDev0/EnergizedPower/assets/37939362/69401460-1e2d-4f19-aa60-6fcee9fa3b4e). Please install Energized power version 1.20.4-2.6.4 or older for NeoForge 20.4.69-beta or older.

**Comment by LunarN0v4** [comment]
Attempted update to 20.4.70-beta, problem appears to be solved.

**Comment by JDDev0** [comment]
Energized power version 1.20.4-2.6.5-neoforge requires NeoForge 20.4.70-beta or newer. If you want to use NeoForge 20.4.69-beta or older you need to install Energized power version 1.20.4-2.6.4-neoforge or older.

NeoForge has introduced a breaking change in the NeoForge networking API in version 20.4.70-beta. FYI NeoForge will most likely introduce more breaking changes until the first stable non-beta release of NeoForge.
