### ISSUE TITLE
Item Conveyor Belt network encoding/decoding problems - Player is sometimes kicked - Caused by Polymer (0.9.9 and older)

### ISSUE THREAD

**Issue by legdna** [JDDev0/EnergizedPower#46]
The player is sometimes kicked from the server with this error:

![Capture d'écran 2024-07-09 211028](https://github.com/user-attachments/assets/2b491b4d-caff-4507-935c-d6f7ccd3bb51)

**Comment by JDDev0** [comment]
Which version of Energized Power are you on?

**Comment by JDDev0** [comment]
Can you please send me the client and server logs and if possible the item data where the player is kicked? (It must be caused by a Item Conveyor Belt; Drop the item and execute `/data get entity @n[type=item]`)

**Comment by legdna** [comment]
The version we are using is 2.12.1 for minecraft 1.21.

I found these logs on the server, but nothing on the client :

```
[22:14:02] [Netty Epoll Server IO #1/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (energizedpower:item_stack_sync)
        at net.minecraft.class_9136.handler$zlo000$fabric-networking-api-v1$encode(class_9136.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
[22:14:02] [Server thread/INFO]: legdna lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (energizedpower:item_stack_sync)
```

**Comment by legdna** [comment]
I don't know what item causes this, all I know is that it happens randomly.

**Comment by JDDev0** [comment]
Can you send me a list of all mods which are installed on the server?

**Comment by JDDev0** [comment]
The problem is caused by an Item Conveyor Belt, but I cannot reproduce the bug.

Can you check where Item Conveyor Belts are used on the server and give me any details which can help me to fix the problem.

**Comment by JDDev0** [comment]
You could also try to update all the mods you are using on the server and on the client and check if the bug is still present.

**Comment by legdna** [comment]
I've tried updating the mods on both the server and the client but this hasn't solved the problem. I've also updated the fabric loader version to 0.16.0 but the problem persists.

**Comment by legdna** [comment]
The only items that regularly appear in the conveyor belt are music discs, iron and flowers, as I have an iron farm. There are also potatoes (potato farm) and carrots (carrot farm).

**Comment by legdna** [comment]
The bug happens randomly, so it can sometimes take over an hour before I'm kicked off the server.

Here's a link to download the modpack to make your search easier:

[Modpack](https://xn--oracls-7ua.fr/oracles-modpack.zip)

And here's the list of mods on the server:

- Xaero's World Map [1.38.8]
- Iris [1.7.3+mc1.21]
- YetAnotherConfigLib [3.5.0+1.21-fabric]
- Waystones [21.0.8]
- Reinforced Shulker Boxes [3.1.0+1.21]
- Beautify [1.2.1+1.21]
- PolyDecorations [0.4.2+1.21]
- Universal Graves [3.4.3+1.21]
- Architectury [13.0.6]
- BlossomTpa [2.2.4+1.21]
- Polymorph [1.0.4+1.21]
- Just Hammers [21.0.2]
- Xaero's Minimap [24.2.1]
- Reinforced Chests [3.0.1+1.21]
- FancyMenu [3.2.5]
- Balm [21.0.14]
- Fabric Language Kotlin [1.11.0+kotlin.2.0.0]
- Dungeons and Taverns Swamp Hut Overhaul [1-v2]
- Mod Menu [11.0.1]
- Simple Voice Chat Music [0.2.0]
- Dungeons and Taverns Pillager Outpost Overhaul [1-v2.2]
- Collective [7.80]
- Photography [1.0.4+mc1.21]
- Indium [1.0.34+mc1.21]
- Too Many Paintings! [1.0.2-1.21-fabric]
- Roguelike Dungeons [2.0.8-1.21-fabric]
- Dungeons and Taverns Stronghold Rework [1-v2.1]
- BackSlot [1.2.15]
- Sodium [0.5.11+mc1.21]
- Reinforced Barrels [2.5.1+1.21]
- Cloth Config v15 [15.0.128]
- Continuity [3.0.0-beta.5+1.21]
- Polymer [0.9.9+1.21]
- Just Player Heads [4.1]
- Dungeons and Taverns Woodland Mansion Overhaul [1-v1.1]
- FallingTree [1.21.0.6]
- GlitchCore [2.0.0.2]
- EpheroLib [1.2.0-1.20.6]
- Melody [1.0.10]
- Simple Voice Chat [1.21-2.5.19]
- Chisel Refabricated [1.8.1]
- Get Off My Lawn ReServed [1.13.1+1.21]
- Advancement Plaques [1.6.6]
- Nemo's Carpentry [2.5.1-1.21]
- Anvil Never Too Expensive [1.2]
- Forge Config API Port [21.0.7]
- Dungeons and Taverns Ancient City Overhaul [1-v2]
- Dynamic FPS [3.6.3]
- Music Sync [1.3]
- Dungeons and Taverns [1-v4.3]
- Polydex [1.2.3+1.21]
- Universal Shops [1.7.1+1.21]
- Iceberg [1.2.4]
- Fabric API [0.100.8+1.21]
- 3d-Skin-Layers [1.6.6]
- Konkrete [1.9.9]
- Roughly Enough Items [16.0.744]
- TerraBlender [4.0.0.1]
- Factory Blocks Mod [1.3.2]
- Energized Power [1.21-2.12.1-fabric]
- Lithium [0.12.7]
- BiomesOPlenty [21.0.0.11]
- Oracles [1.1.0]
- BlossomLib [2.5.8+1.21]
- Croptopia [3.0.9]

**Comment by PixelAlus** [comment]
Hello, we have the same Problem since a few days.
Before the Problem starts we Updated all our Mods and i deleted a "Big Farm" with a lot of "Pflanzenwachstumskammer" and "Itemförderband" i don´t know item names in english, i think Plantgrownchamber and Item Conveyor Belt and used the /fill command for this. After the first time i reload a backup, but it´s don´t help.

Mods we used Client and Server Side
athena-fabric-1.21-4.0.1
breakerplacer-1.0.2+1.21
chipped-fabric-1.21.1-4.0.2
energizedpower-1.21.1-2.12.4
fabric-api-0.114.0+1.21.1
Jade-1.21.1-Fabric-15.9.2
mcw-bridges-3.0.0-mc1.21.1fabric.jar
mcw-doors-1.1.1-mc1.21.1fabric.jar
mcw-fences-1.1.2-mc1.21.1fabric.jar
mcw-furniture-3.3.0-mc1.21.1fabric.jar
mcw-holidays-1.1.0-mc1.21.1fabric.jar
mcw-lights-1.1.1-mc1.21.1fabric.jar
mcw-paintings-1.0.5-1.21.1fabric.jar
mcw-paintings-1.0.5-1.21fabric.jar
mcw-paths-1.0.5-1.21.1fabric.jar
mcw-roofs-2.3.1-mc1.21.1fabric.jar
mcw-stairs-1.0.0-1.21.1fabric.jar
mcw-windows-2.3.0-mc1.21.1fabric.jar
resourcefullib-fabric-1.21-3.0.11
scarecrowsterritory-1.1.11a-fabric-mc1.21.jar
supermartijn642configlib-1.1.8-fabric-mc1.21.jar
supermartijn642corelib-1.1.18a-fabric-mc1.21.jar
toms_storage_fabric-1.21-2.1.0.jar

Mods we used only Client Side
citresewn-1.2.2+1.21
continuity-3.0.0+1.21
indium-1.0.35+mc1.21
iris-fabric-1.8.0+mc1.21.1
jei-1.21.1-fabric-19.21.0.247

Mods we used only Server Side
CustomNameTags-0.2.3+mc1.21.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
ferritecore-7.0.2-hotfix-fabric.jar
lithium-fabric-0.14.5+mc1.21.1.jar
LuckPerms-Fabric-5.4.140.jar
LuckPerms-Fabric-PlaceholderAPI-Hook.jar
spark-1.10.109-fabric.jar (only me is using Client Side)
styled-chat-2.6.0+1.21.jar
styledplayerlist-3.5.1+1.21.jar
vanilla-permissions-0.2.4+1.21.1.jar
worldedit-mod-7.3.8.jar

Datapacks we used
BetterVanillaBuildingV3.5-Datapack.zip
NoEndermanGrief-[1.21]-v.2.0.1.zip

Resourcepacks we used
Better Birch Leaves V2.1-1.21
BetterVanillaBuildingV3.5-Datapack (Modified)
Clear Glass Pack 1.21
JermsyBoy´s Better Leaves V3.1-1.21

Shader
ComplementaryUnbound_r5.3

Part of the Server Log
`[23:16:10] [Netty Epoll Server IO #5/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (energizedpower:item_stack_sync)
        at net.minecraft.class_9136.handler$zff000$fabric-networking-api-v1$encode(class_9136.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException`

I Can´t find a Client Log from the Disconnects

**Comment by PixelAlus** [comment]
Hey, today i see if i join the server there is this text in the server-log, it´s look like the same text if a player get an disconnet.

"[19:58:16] [Server thread/INFO]: ❤ [OP] PixelAlus joined the game
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException"

Maybe if it´s helps u i can whitelist you to our server, so u can look if u find anything thats make this problem. or i can send u a backup from the word to test it.

**Comment by JDDev0** [comment]
Can you please upload the backup to a could storage service (such as Google Drive or One Drive) and share the link to it.

If you don't want to post the link publicly on this GitHub issue, you can send me the link via email (jddev0@dorneger.at) instead.

**Comment by JDDev0** [comment]
@PixelAlus the crash is caused by the "CustomNameTags" (See: https://github.com/senseiwells/CustomNameTags/issues/8)

**Comment by JDDev0** [comment]
@PixelAlus the bug was fixed in "CustomNameTags" (You can download the latest version here: https://modrinth.com/mod/customnametags/version/0.3.4+1.21.1)
"CustomNameTags" does no longer bundle "Polymer" in the jar.
