### ISSUE TITLE
i think the guide book for this mod may be bugged

### ISSUE THREAD

**Issue by cleynen** [JDDev0/EnergizedPower#49]
the error i get is this

 The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9302.comp_2421()" because "writtenbookcontent" is null

the game will crash if you put the guide book in ur hotbar and you get this message.  granted maybe this happened because I use fabric 
but am not sure. or if forge API could fix it.

**Comment by cleynen** [comment]
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-12-06 09:56:14
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9302.comp_2421()" because "writtenbookcontent" is null
	at knot//net.minecraft.class_1843.method_7888(class_1843.java:533)
	at knot//net.minecraft.class_1799.method_7917(class_1799.java:652)
	at knot//net.minecraft.class_1661.method_7381(class_1661.java:242)
	at knot//net.minecraft.class_1657.method_6007(class_1657.java:596)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2507)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java:312)
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:588)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:268)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:401)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_1843.method_7888(class_1843.java:533)
	at knot//net.minecraft.class_1799.method_7917(class_1799.java:652)
	at knot//net.minecraft.class_1661.method_7381(class_1661.java:242)
	at knot//net.minecraft.class_1657.method_6007(class_1657.java:596)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2507)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java:312)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 7
	Entity Name: CelynenMollgo
	Entity's Exact location: 124.99, -22.00, 655.61
	Entity's Block location: World: (124,-22,655), Section: (at 12,10,15 in 7,-2,40; chunk contains blocks 112,-64,640 to 127,319,655), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:588)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:268)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:401)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 330573512 bytes (315 MiB) / 1912602624 bytes (1824 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 7900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.69
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 12288.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6614
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 512.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.24002.92
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 79495.55
	Virtual memory used (MiB): 68261.20
	Swap memory total (MiB): 47534.21
	Swap memory used (MiB): 1045.84
	Space in storage for jna.tmpdir (MiB): available: 2193692.00, total: 3814806.25
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 2193692.00, total: 3814806.25
	Space in storage for io.netty.native.workdir (MiB): available: 2193692.00, total: 3814806.25
	Space in storage for java.io.tmpdir (MiB): available: 2193692.00, total: 3814806.25
	Space in storage for workdir (MiB): available: 2193692.00, total: 3814806.25
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alternate-current: Alternate Current 1.9.0
		anvilrestoration: Anvil Restoration 2.3
		architectury: Architectury 13.0.8
		betterenchanting: Better Enchanting 0.5.0
		bronze: Bronze 1.0.11+1.21
			trimmed: Trimmed 3.0.0
		cleancontainer: CleanContainer 1.5.0
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.87
		computercraft: CC: Tweaked 1.114.2
			cc_tweaked_cobalt: cobalt 0.9.5
			com_jcraft_jzlib: jzlib 1.1.3
			io_netty_netty-codec-http: netty-codec-http 4.1.97
			io_netty_netty-codec-socks: netty-codec-socks 4.1.97
			io_netty_netty-handler-proxy: netty-handler-proxy 4.1.97
		craftsaddles: Craft Saddles 1.0.1
		cratedelight: Crate Delight 24.11.22-1.21-fabric
		crawl: Crawl 0.13.0
		diamond: Easy Diamond 1.21.1-1.6.8
		energizedpower: Energized Power 1.21.1-2.12.4-fabric
			team_reborn_energy: Energy 4.1.0
		fabric-api: Fabric API 0.105.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.23+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.8.0+9d22c5fd19
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.20+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.0+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.3.0+d831205f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
		farmersdelight: Farmer's Delight 1.21.1-2.2.6+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta.47+1.21.1
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta.47+1.21.1
				porting_lib_asm: Porting Lib ASM 3.1.0-beta.47+1.21.1
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta.47+1.21.1
				porting_lib_common: Porting Lib Common 3.1.0-beta.47+1.21.1
				porting_lib_entity: Porting Lib Entity 3.1.0-beta.47+1.21.1
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta.47+1.21.1
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta.47+1.21.1
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta.47+1.21.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta.47+1.21.1
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta.47+1.21.1
			porting_lib_config: Porting Lib Config 3.1.0-beta.47+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta.47+1.21.1
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta.47+1.21.1
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta.47+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta.47+1.21.1
				mixinextras: MixinExtras 0.5.0-beta.3
				porting_lib_core: Porting Lib Core 3.1.0-beta.47+1.21.1
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta.47+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0-beta.47+1.21.1
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta.47+1.21.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta.47+1.21.1
		forgeconfigapiport: Forge Config API Port 21.1.1
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		ironchest: Iron Chests 2.0.4
			libgui: LibGui 11.1.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.21.0.244
		mcwroofs: Macaw's Roofs 2.3.1
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mr_dungeons_andtavernswoodlandmansionreplacement: Dungeons and Taverns Woodland Mansion Replacement 1-v1.2
		patchouli: Patchouli 1.21-87-FABRIC
			fiber: fiber 0.23.0-2
		redstonepen: Redstone Pen 1.11.41
		rusticdelight: Rustic Delight 1.0.2
		seasons: Fabric Seasons 2.4.2-BETA+1.21
		simple_backpack: SimpleBackpack 1.6.9
			blue_endless_jankson: jankson 1.2.3
		simple_copper_pipes: Simple Copper Pipes 2.0.3
			frozenlib: FrozenLib 1.9.3-mc1.21.1
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		survive: Survive 10.1.4-beta
		tinymobfarm: Tiny Mob Farm Remastered 1.4.1-1.21
		trinkets: Trinkets 3.10.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		uilib: UI Lib 0.3.9-1.21
		unionlib: UnionLib 12.0.7
			com_google_code_findbugs_jsr305: jsr305 3.0.2
		walljump: Wall-Jump TXF 1.21.1-1.2.8-fabric
			configlibtxf: ConfigLib TXF 7.2.5-fabric
			keybindfixtxf: Keybind Fix TXF 1.1.1
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.0
		xp_storage: XP Storage 1.6+1.21
			cardinal-components-item: Cardinal Components API (items) 6.1.0
	Loaded Shaderpack: BSLOriginal_v8.3.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['CelynenMollgo'/7, l='ServerLevel[testing]', x=124.99, y=-22.00, z=655.61]]
	Active Data Packs: vanilla, fabric, betterenchanting, bronze, collective, computercraft (incompatible), craftsaddles, cratedelight, diamond, energizedpower (incompatible), fabric-convention-tags-v2, farmersdelight, frozenlib, ironchest, mcwroofs (incompatible), mr_dungeons_andtavernswoodlandmansionreplacement, patchouli (incompatible), porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, redstonepen (incompatible), rusticdelight, seasons, simple_backpack, simple_copper_pipes, survive (incompatible), tinymobfarm, trinkets, unionlib (incompatible), walljump, xp_storage
	Available Data Packs: betterenchanting, bronze, bundle, collective, computercraft (incompatible), craftsaddles, cratedelight, diamond, energizedpower (incompatible), fabric, fabric-convention-tags-v2, farmersdelight, frozenlib, ironchest, mcwroofs (incompatible), mr_dungeons_andtavernswoodlandmansionreplacement, patchouli (incompatible), porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, redstonepen (incompatible), rusticdelight, seasons, simple_backpack, simple_copper_pipes, survive (incompatible), tinymobfarm, trade_rebalance, trinkets, unionlib (incompatible), vanilla, walljump, xp_storage
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 2027323090699677770
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.9-1.21.1
```
this is the crash report I got.
